// Manually made the `ScheduleLeaderboard` struct, an extension of `Objects.Protobuf` type.


// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ScheduleLeaderboard.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

extension DTOs.Protobuf {
    struct ScheduleLeaderboard {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.
        
        var items: [ScheduleLeaderboard.Item] = []
        
        var unknownFields = SwiftProtobuf.UnknownStorage()
        
        struct Item {
            // SwiftProtobuf.Message conformance is added in an extension below. See the
            // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
            // methods supported on all messages.
            
            var tag: String = String()
            
            var name: String = String()
            
            var trophies: Int32 = 0
            
            var unknownFields = SwiftProtobuf.UnknownStorage()
            
            init() {}
        }
        
        init() {}
    }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DTOs.Protobuf.ScheduleLeaderboard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "ScheduleLeaderboard"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "items"),
    ]
    
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
            default: break
            }
        }
    }
    
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.items.isEmpty {
            try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    static func ==(lhs: Self, rhs: Self) -> Bool {
        if lhs.items != rhs.items {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}

extension DTOs.Protobuf.ScheduleLeaderboard.Item: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Self.protoMessageName + ".Item"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "tag"),
        2: .same(proto: "name"),
        3: .same(proto: "trophies"),
    ]
    
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularStringField(value: &self.tag) }()
            case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
            case 3: try { try decoder.decodeSingularInt32Field(value: &self.trophies) }()
            default: break
            }
        }
    }
    
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.tag.isEmpty {
            try visitor.visitSingularStringField(value: self.tag, fieldNumber: 1)
        }
        if !self.name.isEmpty {
            try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
        }
        if self.trophies != 0 {
            try visitor.visitSingularInt32Field(value: self.trophies, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    static func ==(lhs: Self, rhs: Self) -> Bool {
        if lhs.tag != rhs.tag {return false}
        if lhs.name != rhs.name {return false}
        if lhs.trophies != rhs.trophies {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}

// MARK: - Extensions Added by me


// Changing `respValue` or `respScore` will likely end up breaking
// `DTOs.Redis.Player`'s stuff... Be careful.
extension DTOs.Protobuf.ScheduleLeaderboard.Item {
    var respValue: String {
        "\(self.tag)@%&*\(self.name)"
    }
    
    func respScore(timeInterval: Int) -> Double {
        Double("\(self.trophies)\(timeInterval)") ?? 0
    }
}
